=== dcwise/d4p-sample-data/Open_University_MU120_4M2/metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Jenny Gray (The Open University) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="unit">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="identifier" type="xs:string"/>
				<xs:element name="url" type="xs:anyURI" minOccurs="0"/>
				<xs:element name="location">
					<xs:annotation>
						<xs:documentation>lab or learn</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="locationType"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="status" default="Current" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="statusType"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="title" type="xs:string"/>
				<xs:element name="description" type="xs:string">
					<xs:annotation>
						<xs:documentation>introductory text</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="source" type="xs:string"/>
				<xs:element name="authors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="educationalDescription" type="LearningOutcomesType" minOccurs="0">
					<xs:annotation>
						<xs:documentation>learning aims and objectives</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="rights" type="rightsType" minOccurs="0"/>
				<xs:element name="classificationKeywords">
					<xs:annotation>
						<xs:documentation>course categories</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="keyword" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="date" type="xs:date">
					<xs:annotation>
						<xs:documentation>last updated date</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="version" type="xs:string" default="1.0"/>
				<xs:element name="prerequisites" type="xs:string" minOccurs="0"/>
				<xs:element name="level" type="levelType"/>
				<xs:element name="time" type="xs:nonNegativeInteger"/>
				<xs:element name="relations" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="relation" type="relationStructure" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="locationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="lab"/>
			<xs:enumeration value="learn"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="statusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Current"/>
			<xs:enumeration value="Archive"/>
            <xs:enumeration value="Public"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="LearningOutcomesType">
		<xs:sequence>
			<xs:element name="Paragraph" type="ParagraphType"/>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="LearningOutcome" type="InlineType"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ParagraphType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="b"/>
			<xs:element ref="i"/>
			<xs:element ref="u"/>
			<xs:element ref="sup"/>
			<xs:element ref="sub"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="b" type="InlineType">
		<xs:annotation>
			<xs:documentation>bold</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="i" type="InlineType">
		<xs:annotation>
			<xs:documentation>italic</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="u" type="InlineType">
		<xs:annotation>
			<xs:documentation>underline</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="sup" type="InlineType">
		<xs:annotation>
			<xs:documentation>superscript</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="sub" type="InlineType">
		<xs:annotation>
			<xs:documentation>subscript</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="InlineType" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="b"/>
			<xs:element ref="i"/>
			<xs:element ref="u"/>
			<xs:element ref="sup"/>
			<xs:element ref="sub"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="rightsType">
		<xs:sequence>
			<xs:element name="Paragraph" type="ParagraphType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="relationStructure">
		<xs:sequence>
			<xs:element name="url" type="xs:anyURI"/>
			<xs:element name="urltitle" type="xs:string"/>
			<xs:element name="urlgroup" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="levelType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="introductory"/>
			<xs:enumeration value="intermediate"/>
			<xs:enumeration value="advanced"/>
			<xs:enumeration value="masters"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dcwise/d4p-sample-data/Open_University_S357_1/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<unit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/OCI/metadata.xsd">
<identifier>S357_1</identifier>
<url>http://openlearn.open.ac.uk/course/view.php?id=3639</url>
<location>learn</location>
<title>The Big Bang</title>
<description>‘This is the way the world ends / Not with a bang but a whimper.’ (T.S. Eliot) But how about the way the world begins? Was this the biggest bang of all? This unit will introduce you to the theory of the Big Bang and will present the three main lines of experimental evidence that support this theory.
</description>
<source/>
<authors>
	<author/>
</authors>
<educationalDescription>
	<Paragraph>By the end of this unit you will know how to:</Paragraph>
			<LearningOutcome>Describe the characteristics of light emitted by stars, and hence the
information of cosmological interest that can be deduced from it;</LearningOutcome>
			<LearningOutcome>Distinguish between true and false statements relevant to the
distribution and motion of stars within galaxies, and of galaxies within
clusters and superclusters;</LearningOutcome>
<LearningOutcome>Outline the methods used for estimating the distances to stars and to
galaxies;</LearningOutcome>
<LearningOutcome>Explain and apply Hubble’s law;</LearningOutcome>
<LearningOutcome>Distinguish between various sources of redshift and estimate their
relative importance in a given situation;</LearningOutcome>
<LearningOutcome>Describe the cosmic microwave radiation in terms of its origin, its
thermal nature, and how its temperature has changed with time;</LearningOutcome>
<LearningOutcome>Explain how observations of thermal radiation are affected by the
motion of the observer with respect to it;</LearningOutcome>
<LearningOutcome>Outline the evidence concerning the isotropy of the Universe;</LearningOutcome>
<LearningOutcome>Describe the most important basic nuclear reactions taking place in the
early stages of the big bang, and how the final mix of elements produced
provides evidence today for the big bang.</LearningOutcome>
</educationalDescription>
<rights>
	<Paragraph/>
</rights>
<classificationKeywords><keyword>Science and Nature</keyword><keyword>gravity</keyword><keyword>mass</keyword><keyword>acceleration</keyword><keyword>energy</keyword><keyword>big_bang</keyword></classificationKeywords>
<date>2008-03-14</date>
<version>1.0</version>
<prerequisites/>
<level>advanced</level>
<time>20</time>
<relations>
<relation>
<url>http://www3.open.ac.uk/courses/bin/p12.dll?C01S357</url>
<urltitle>An OU course on this topic</urltitle>
<urlgroup>OU Links</urlgroup>
</relation>
<relation>
<url>http://www3.open.ac.uk/courses/classifications/science.shtm</url>
<urltitle>Study this topic at the OU</urltitle>
 <urlgroup>OU Links</urlgroup>
</relation>
<relation>
<url>http://www.open2.net/sciencetechnologynature</url>
<urltitle>open2.net: Science &amp; Nature</urltitle>
 <urlgroup>OU Links</urlgroup>
</relation>
</relations>
</unit>
